logging:
  file:
    name: job-database.log
detection:
  #  type: DATA (xuất data table), DLL (xuất DLL), TELNET (kiểm tra ip)
  type-code: DLL
  #   nếu type = DATA --> module.type: ALL(xuất all table) != ALL(xuất table được chỉ định module.table)
  module:
    type: ALL
    table: lib_document,lib_linhvuc,lib_document_phanphoi,lib_document_attach,fem_file,lib_document_phanphoi_act_his
